services:
  backend:
    container_name: backend
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app/
    ports:
      - "4000:4000"
    command: npm run start:backend
    tty: true
    stdin_open: true

  frontend:
    container_name: frontend
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app/
    working_dir: /app/apps/frontend
    ports:
      - "3000:3000"
    command: npm run dev
    tty: true
    stdin_open: true
    depends_on:
      - backend
